### ISSUE TITLE
Test levels

### ISSUE THREAD

**Issue by karsten2004** [FIS-game-development-club/2018#33]
Test levels tent to break quite a lot.
therefore I'd like to propose that whenever we create a branch we create a test level for the corresponding the branch to fix any future complications

**Comment by Frederik-Hollis** [comment]
OK!
But what if I'm making level 2?

**Comment by michael-portiera** [comment]
Lets make it a rule that the branch name and scene name must be the same.

**Comment by Frederik-Hollis** [comment]
yup
