### ISSUE TITLE
More traps!

### ISSUE THREAD

**Issue by Frederik-Hollis** [FIS-game-development-club/2018#46]
IDEAS NEEDED!!!

**Comment by Frederik-Hollis** [comment]
Fireball gun, rapidly opening trapdoor (moving platform with no friction)

also, a hint that there is a trap there???

**Comment by Frederik-Hollis** [comment]
Fireball gun, rapidly opening trapdoor (moving platform with no friction)

also, a hint that there is a trap there???

Just ideas

**Comment by karsten2004** [comment]
there is a trap where?

**Comment by Frederik-Hollis** [comment]
@karsten2004 : there is a trap where? --- a hint so you know, for example where spikes will come up - eg. red floor...

**Comment by Frederik-Hollis** [comment]
ok... bye
