### ISSUE TITLE
Spikes fix needs to be implemented into level1/2/3

### ISSUE THREAD

**Issue by karsten2004** [FIS-game-development-club/2018#88]
I have redone most of the spikes assets and completely redone the spikes assets organization and prefabs, any problems like all the spikes disappearing and acting weird shouldn't be able to happen in the future from this point forth. For any questions on how the new 3x3 moving spikes (and possibly regular moving spikes) work, please respond on this issue.

**Comment by karsten2004** [comment]
Just a short explanation on the new 3x3 moving spikes centralized variables. on the parent 3x3 object there is a script applied called "Spikegroup" this holds the variables: shifstpeed, timeup, and timedown (you should ignore "y"). you can set them in there so you shouldn't have to set them for each moving spikes individually. in every moving spike there is a script applied that asks for "parent" this is what it is talking about (it should already be applied, however).  Inside 3x3 moving spikes as a folder, there should also be an object known as Position 2 you can use this to set how high you want the spikes to move.

**Comment by Frederik-Hollis** [comment]
working on it now

**Comment by Frederik-Hollis** [comment]
P.S. Level 1 has no 3x3 spikes so its ok

**Comment by Frederik-Hollis** [comment]
OK gooooood sooo...

CLOSE!

**Comment by Frederik-Hollis** [comment]
ahhh... feels good to close issues
