### ISSUE TITLE
Spikes are broken (still)

### ISSUE THREAD

**Issue by Frederik-Hollis** [FIS-game-development-club/2018#90]
Spikes are broken (still)

**Comment by Frederik-Hollis** [comment]
https://user-images.githubusercontent.com/32100502/38639710-5d3c21e6-3dd2-11e8-916b-7d9f831a28b9.png

**Comment by karsten2004** [comment]
should be all fixed now👨🏼‍💻

**Comment by karsten2004** [comment]
I suggest you try it again
